"""empty message

Revision ID: 45e4d05f9f0d
Revises: f9bdf561b0c5
Create Date: 2022-12-08 22:21:57.089643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45e4d05f9f0d'
down_revision = 'f9bdf561b0c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('choice', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(length=140),
               type_=sa.String(length=256),
               existing_nullable=True)

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(length=140),
               type_=sa.String(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=140),
               existing_nullable=True)

    with op.batch_alter_table('choice', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=140),
               existing_nullable=True)

    # ### end Alembic commands ###
