"""empty message

Revision ID: 0123b5356527
Revises: 8f538197ac43
Create Date: 2022-11-30 21:15:27.411581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0123b5356527'
down_revision = '8f538197ac43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cupon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('procent', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cupon'))
    )
    op.create_table('user_cupon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cupon_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cupon_id'], ['cupon.id'], name=op.f('fk_user_cupon_cupon_id_cupon')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_cupon_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_cupon'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_cupon')
    op.drop_table('cupon')
    # ### end Alembic commands ###
